# Generated by Django 2.1.7 on 2019-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_name',
            field=models.CharField(default='urlname', max_length=64),
            preserve_default=False,
        ),
    ]
