# Generated by Django 2.1.7 on 2019-04-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_menu_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='practice.Job'),
        ),
    ]
