# Generated by Django 2.1.7 on 2019-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20190414_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='result',
            field=models.BooleanField(),
        ),
    ]
