# Generated by Django 2.1.7 on 2019-04-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_auto_20190416_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekrecord',
            name='readed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='result',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weekrecord',
            name='recordContent',
            field=models.CharField(max_length=4096),
        ),
    ]
