# Generated by Django 2.1.7 on 2019-04-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_auto_20190416_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekrecord',
            name='recordtitle',
            field=models.CharField(default='标题2019', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weekrecord',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
