# Generated by Django 2.1.7 on 2019-04-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_auto_20190416_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weekrecord',
            old_name='recordtitle',
            new_name='recordTitle',
        ),
    ]
